"""Candidate-rule funnel of the frozen run: for every probe family, how many assertions, series and transitions it produced,
and how its events were classified (from oracle/event_classification.json). Also lists the candidate recurrences examined
by hand (evidence log, CANDIDATES.md) with their outcome. Output: evidence/CANDIDATE_RULES.md"""
import json, glob, os, re, collections
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
R = "oracle/results_v1"
def family(key):
    if key.startswith("f2:"): return "F2"
    k = key.split(":", 1)[1]
    m = re.match(r"(F\d+|G)", k); return m.group(1)
DESC = {"F1": "directory membership follows path segments, not string prefixes", "F2": "recursive delete removes directory markers",
        "F3": "object keys round-trip exactly (put/get; copy/rename)", "F4": "listings complete beyond one result page",
        "F6": "trailing-slash equivalence", "F7": "marker-only directories", "F8": "missing paths", "F9": "double slashes in keys",
        "F10": "spaces in directory names", "F11": "spaces / special directory names in listings", "F13": "rmdir semantics",
        "F14": "file/directory exclusivity", "F15": "directory move boundaries", "F16": "directory copy boundaries",
        "F17": "trailing slash on files", "G": "glob basics"}
series = collections.defaultdict(dict)
for d in glob.glob(f"{R}/*__*"):
    orc, be = os.path.basename(d).split("__")
    for f in glob.glob(f"{d}/*.json"):
        cl = os.path.basename(f).split("-", 1)[0]; r = json.load(open(f))
        if orc == "f2":
            for v, x in r["variants"].items():
                for a in ("A_nothing_under_d", "B_sibling_prefix_survives"): series[(cl, be, f"f2:{v}:{a}")][f] = x[a]
        else:
            for k, p in r["probes"].items():
                if p["pass"] is not None: series[(cl, be, f"{orc}:{k}")][f] = p["pass"]
fam = collections.defaultdict(lambda: {"assertions": set(), "series": 0, "flipping_series": 0, "always_fail": 0, "events": collections.Counter()})
for (cl, be, k), vs in series.items():
    F = fam[family(k)]; F["assertions"].add(k); F["series"] += 1
    vals = set(vs.values())
    if len(vals) > 1: F["flipping_series"] += 1
    elif vals == {False}: F["always_fail"] += 1
ev = json.load(open("oracle/event_classification.json"))["events"]
for e in ev:
    for f in sorted({family(p) for p in e["probes"]}):
        fam[f]["events"][e["category"] + (f" ({e['case']})" if e["case"] else "")] += 1
order = sorted(fam, key=lambda f: (f != "G", int(re.sub(r"\D", "", f) or 99)))
L = ["# Candidate-rule funnel (frozen run)", "",
     "Generated by `oracle/candidate_funnel.py` from `oracle/results_v1` and `oracle/event_classification.json`.",
     "A series is one assertion on one client/backend pair across its releases; an event may involve several families.", "",
     "| Family | Rule under test | Assertions | Series | Series with a flip | Series failing in every release | Events (classification) |",
     "|---|---|---:|---:|---:|---:|---|"]
for f in order:
    F = fam[f]; evs = "; ".join(f"{k} ×{n}" for k, n in sorted(F["events"].items())) or "none"
    L.append(f"| {f} | {DESC.get(f, '')} | {len(F['assertions'])} | {F['series']} | {F['flipping_series']} | {F['always_fail']} | {evs} |")
L += ["", "Totals: " + f"{sum(len(F['assertions']) for F in fam.values())} assertion ids (f2 counted per variant and assertion), "
      f"{sum(F['series'] for F in fam.values())} series, {sum(F['flipping_series'] for F in fam.values())} with a flip.", "",
      "## Candidate recurrences examined by hand (evidence log)", "",
      "| Candidate | Implementations | Outcome | Reason |", "|---|---|---|---|",
      "| Placeholder directories (topic pairing) | gcsfs #458/#459, s3fs #988/#989 | rejected | no single assertion separates both: two different defects |",
      "| find() must not change later ls() (directory cache) | s3fs (2021, 2023, 2025), gcsfs (2022) | shared origin | gcsfs code path ported from s3fs by the same author three days later (2020); fails lineage condition 5 |",
      "| Relative paths in makedirs | gcsfs #618, fsspec sftp #1451 | rejected | different behaviour (local vs remote resolution) |",
      "| Listing includes the directory's own marker | s3path, cloudpathlib, OpenDAL, s3fs, Arrow | contested | implementations changed in opposite directions |",
      "| Glob correctness | s3path, cloudpathlib, s3fs | excluded | 44-commit refactoring without identifiable fix; pre-regression failure; flip in inherited fsspec code |",
      "| Trailing slash on a file (F17) | cloudpathlib, gcsfs, OpenDAL | contested / single | implementations disagree; no lineage-independent pair with one assertion |",
      "| rmdir on a non-empty directory | s3path #205 vs others | not a recurrence | design choice under discussion, no fix event |",
      "| Recursive delete removes markers (F2) | Arrow, s3fs | Golden Case GC1 | — |",
      "| Keys equal the user's string, put/get (F3) | s3path, gcsfs, object_store | Golden Case GC2a | — |",
      "| Copy/rename use the exact source key (F3b) | Arrow, object_store | Golden Case GC2b | — |",
      "| foo does not exist because foobar does (F1) | cloudpathlib, OpenDAL | Golden Case GC3 | — |",
      "| Directory move/copy boundaries (F15/F16) | gcsfs (fix), s3path (live violation) | prospective case PV1 | s3path has no history for the rule |",
      "", "Before the cross-language study, a screen of fsspec's built-in backends (2,512 pre-2026 commits → 409 fixes → 20 "
      "methods fixed in ≥2 backends) yielded about three same-rule groups, all within the fsspec lineage; this motivated "
      "moving to lineage-independent clients (see CANDIDATES.md)."]
OUTCOME = {  # outcome of each candidate rule (probe family), from the events above
 "F4": "no transition in any tested release", "F6": "no transition in any tested release", "F8": "no transition in any tested release",
 "F10": "no transition in any tested release", "F11": "no transition in any tested release", "F14": "no transition in any tested release",
 "G": "transitions without an attributable fix (excluded)",
 "F7": "conflicting semantics (contested)", "F17": "conflicting semantics (contested)",
 "F9": "fixed in one implementation only", "F13": "fixed in one implementation only",
 "F15": "fixed in one implementation only", "F16": "fixed in one implementation only",
 "F1": "same-assertion fixes in >=2 lineage-independent implementations (Golden)",
 "F2": "same-assertion fixes in >=2 lineage-independent implementations (Golden)",
 "F3": "same-assertion fixes in >=2 lineage-independent implementations (Golden)"}
assert set(OUTCOME) == set(fam), set(fam) ^ set(OUTCOME)
summ = collections.defaultdict(list)
for f in order: summ[OUTCOME[f]].append(f)
L += ["", "## Summary: every candidate rule by outcome", "", "| Outcome | Rules | Which |", "|---|---:|---|"]
for o, fs in summ.items(): L.append(f"| {o} | {len(fs)} | {', '.join(fs)} |")
L += ["| rejected on reading: different behaviours (earlier candidate) | 1 | relative paths in makedirs |",
      "| fixed in >=2 implementations, but no single assertion separates both (earlier candidate) | 1 | placeholder directories |",
      "| fixed in >=2 implementations with shared code origin (earlier candidate) | 1 | directory cache |",
      f"| **total** | {len(order) + 3} | 16 probe families + 3 earlier candidates; Golden families F1, F2, F3 give GC3, GC1, GC2a/GC2b |"]
os.makedirs("evidence", exist_ok=True); open("evidence/CANDIDATE_RULES.md", "w").write("\n".join(L) + "\n"); print("\n".join(L[:26]))
